name: cafecanva_analytics
description: Interactive visual analytics and financial reporting charts for CafeCanva.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cafecanva_core:
    path: ../cafecanva_core
  cafecanva_ui:
    path: ../cafecanva_ui
