name: cafecanva_ui
description: Premium design system, theme tokens, and reusable responsive widgets for CafeCanva.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  cafecanva_core:
    path: ../cafecanva_core
