directories:
  output: release
  buildResources: build
appId: bar.cafecanvas.storeadmin
productName: Cafe Canvas Store Admin
copyright: Copyright © 2025 Cafe Canvas
files:
  - filter:
      - dist/**
      - dist-electron/**
      - resources/**
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: resources/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: resources/icon.ico
  uninstallerIcon: resources/icon.ico
  installerHeaderIcon: resources/icon.ico
  createDesktopShortcut: always
  createStartMenuShortcut: true
  shortcutName: Cafe Canvas Store Admin
publish:
  provider: github
  owner: Yashzagde
  repo: Cafe-Canava-Desktop
electronVersion: 31.7.7
